-- Question-bank expansion (roadmap.md "Now" phase).
-- Coverage is modeled on the standard Exponent / IGotAnOffer question banks but
-- every prompt is written in our own words (see docs/ai-rules.md — don't copy
-- source material verbatim).
--   product_sense / analytical_execution / leadership_principles_behavioral: +10 each (6 -> 16)
--   strategy_business / estimation: +10 each (0 -> 10) — these rubrics were already
--     complete in rubrics-amazon.json, they just had no questions, so adding them
--     turns two previously-dead dropdown options into working ones.
-- Idempotent: guarded by NOT EXISTS on title so re-running doesn't duplicate.

insert into questions (company, type, title, description, metadata)
select 'amazon', v.type, v.title, v.description, v.metadata::jsonb
from (values
  -- ---------- product_sense (+10) ----------
  ('product_sense', 'Design an Amazon feature for new parents.',
   'Amazon wants to better serve customers who have just had a baby. Design a feature or experience for this segment.',
   '{"difficulty":"mid","tags":["new_segment","personalization"]}'),
  ('product_sense', 'Improve the gift-buying experience on Amazon.',
   'Buying gifts on Amazon can be stressful — choosing the right item, hiding the price, getting it delivered on time. Design a better gifting experience.',
   '{"difficulty":"mid","tags":["gifting","customer_obsession"]}'),
  ('product_sense', 'Design a feature to help Amazon Fresh customers reduce food waste.',
   'Many grocery customers throw away food they never used. Design a feature that helps Amazon Fresh customers waste less.',
   '{"difficulty":"senior","tags":["grocery","sustainability"]}'),
  ('product_sense', 'Design a shopping experience for visually impaired customers.',
   'How would you design an Amazon shopping experience that works well for customers with low vision or blindness?',
   '{"difficulty":"senior","tags":["accessibility","inclusive_design"]}'),
  ('product_sense', 'Rebuild trust in Amazon product reviews.',
   'Some customers no longer trust product reviews because of fake or incentivized ratings. How would you redesign the review system to rebuild trust?',
   '{"difficulty":"senior","tags":["trust","reviews"]}'),
  ('product_sense', 'Design a single place for customers to manage all their Amazon subscriptions.',
   'Customers often lose track of their Subscribe & Save items, Prime add-ons, and digital subscriptions. Design a hub to manage them all.',
   '{"difficulty":"mid","tags":["subscriptions","account_management"]}'),
  ('product_sense', 'Improve the Kindle reading experience for students.',
   'Students use Kindle for textbooks and study material. Design features that make Kindle meaningfully better for studying.',
   '{"difficulty":"mid","tags":["kindle","education"]}'),
  ('product_sense', 'Design a group-buying experience for Amazon.',
   'Amazon wants to let groups of customers buy things together (e.g. for a shared household or an event). Design the v1 experience.',
   '{"difficulty":"senior","tags":["new_product","social"]}'),
  ('product_sense', 'Reduce delivery anxiety for Amazon customers.',
   'Customers often feel anxious about whether a package will actually arrive on time, especially for time-sensitive orders. Design a feature to reduce that anxiety.',
   '{"difficulty":"mid","tags":["delivery","trust"]}'),
  ('product_sense', 'Design an Amazon feature for a country Amazon is newly entering.',
   'Amazon is launching in a market where most people are shopping online for the first time and card penetration is low. Design a feature to win these first-time customers.',
   '{"difficulty":"senior","tags":["emerging_markets","new_segment"]}'),

  -- ---------- analytical_execution (+10) ----------
  ('analytical_execution', 'Prime membership renewals dropped 10% this month.',
   'Monthly Prime renewals fell 10% versus last month. Walk through how you would investigate and what you would do.',
   '{"difficulty":"mid","tags":["metrics","retention"]}'),
  ('analytical_execution', 'How would you measure the success of one-click checkout?',
   'Amazon is evaluating its one-click checkout flow. Define the metrics you would use to judge whether it is successful.',
   '{"difficulty":"mid","tags":["metrics","checkout"]}'),
  ('analytical_execution', 'Cart abandonment on mobile web increased 15%.',
   'The share of customers who add items to cart but do not check out rose 15% on mobile web. Diagnose the possible causes.',
   '{"difficulty":"mid","tags":["metrics","conversion","mobile"]}'),
  ('analytical_execution', 'A group of sellers report their sales suddenly dropped.',
   'Several third-party sellers say their sales fell sharply this week. How would you determine whether this is a platform-wide problem or something else?',
   '{"difficulty":"senior","tags":["metrics","marketplace"]}'),
  ('analytical_execution', 'Define success metrics for same-day delivery.',
   'Amazon is expanding same-day delivery. What metrics would you track to know whether it is working, for both customers and the business?',
   '{"difficulty":"mid","tags":["metrics","logistics"]}'),
  ('analytical_execution', 'Time-to-first-purchase for new Prime members increased.',
   'New Prime members are taking longer to make their first purchase after signing up. Walk through how you would investigate.',
   '{"difficulty":"senior","tags":["metrics","activation"]}'),
  ('analytical_execution', 'An A/B test raised engagement but slightly lowered conversion.',
   'A new feature increased time-on-site and engagement but reduced purchase conversion by a small amount in an A/B test. How would you decide whether to launch it?',
   '{"difficulty":"senior","tags":["experimentation","tradeoffs"]}'),
  ('analytical_execution', 'Search click-through is up but purchase conversion is flat.',
   'Customers are clicking on more search results than before, but the rate at which they buy has not changed. What might be going on?',
   '{"difficulty":"senior","tags":["metrics","search"]}'),
  ('analytical_execution', 'How would you measure whether Alexa is a successful product?',
   'Define what success looks like for Alexa and the metrics you would use to measure it.',
   '{"difficulty":"mid","tags":["metrics","alexa"]}'),
  ('analytical_execution', 'On-time delivery rate dropped in one region.',
   'The on-time delivery rate fell noticeably in a single region last week while staying flat elsewhere. Walk through your diagnosis.',
   '{"difficulty":"mid","tags":["metrics","operations"]}'),

  -- ---------- leadership_principles_behavioral (+10) ----------
  ('leadership_principles_behavioral', 'Tell me about a time you failed.',
   'Describe a real failure, what you did, and what you learned from it.',
   '{"difficulty":"mid","tags":["Learn and Be Curious","Deliver Results"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you had to dive deep into data to solve a problem.',
   'Walk through how you got into the details, what you found, and the outcome.',
   '{"difficulty":"mid","tags":["Dive Deep"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you simplified a complex process.',
   'Describe the process, how you simplified it, and the impact.',
   '{"difficulty":"mid","tags":["Invent and Simplify"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you put the customer first even when it was costly.',
   'Describe the situation, the trade-off, and what you decided.',
   '{"difficulty":"mid","tags":["Customer Obsession"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you had to say no to a stakeholder.',
   'Walk through how you handled the pushback and what the outcome was.',
   '{"difficulty":"mid","tags":["Have Backbone; Disagree and Commit","Earn Trust"]}'),
  ('leadership_principles_behavioral', 'Tell me about the most innovative idea you have had.',
   'Describe the idea, how you pursued it, and what happened.',
   '{"difficulty":"senior","tags":["Think Big","Invent and Simplify"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you handled competing priorities.',
   'Describe how you decided what to focus on and what you delivered.',
   '{"difficulty":"mid","tags":["Deliver Results","Are Right, A Lot"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you improved something that was already working.',
   'Describe what you improved, why, and the result.',
   '{"difficulty":"mid","tags":["Insist on the Highest Standards"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you earned the trust of a skeptical team.',
   'Walk through how you built credibility and what changed.',
   '{"difficulty":"senior","tags":["Earn Trust"]}'),
  ('leadership_principles_behavioral', 'Tell me about a time you took a calculated risk.',
   'Describe the risk, how you evaluated it, and the outcome.',
   '{"difficulty":"mid","tags":["Bias for Action"]}'),

  -- ---------- strategy_business (new, +10) ----------
  ('strategy_business', 'Should Amazon expand more aggressively into online pharmacy?',
   'Evaluate whether Amazon should push harder into the online pharmacy market, and how you would approach it.',
   '{"difficulty":"senior","tags":["market_entry","healthcare"]}'),
  ('strategy_business', 'How should Amazon grow Prime Video over the next three years?',
   'Lay out a strategy for growing Prime Video and how it fits Amazon''s broader ecosystem.',
   '{"difficulty":"senior","tags":["growth","media"]}'),
  ('strategy_business', 'Should Amazon build its own last-mile delivery network?',
   'Evaluate the trade-offs of Amazon building out its own last-mile delivery versus relying on third-party carriers.',
   '{"difficulty":"senior","tags":["logistics","build_vs_buy"]}'),
  ('strategy_business', 'How would you grow Amazon''s advertising business?',
   'Advertising is one of Amazon''s fastest-growing areas. How would you think about growing it further without hurting the customer experience?',
   '{"difficulty":"senior","tags":["monetization","ads"]}'),
  ('strategy_business', 'Where should Amazon Fresh expand next, and how would you prioritize?',
   'Amazon Fresh can only expand to a limited number of new cities next year. How would you decide where to go?',
   '{"difficulty":"mid","tags":["prioritization","grocery"]}'),
  ('strategy_business', 'How should Amazon respond to a fast-growing competitor in a key category?',
   'A competitor is rapidly gaining share in an important category. How should Amazon respond?',
   '{"difficulty":"senior","tags":["competition","defense"]}'),
  ('strategy_business', 'Should Amazon offer a single bundled subscription across its services?',
   'Evaluate whether Amazon should bundle Prime, Music, and other services into one subscription, and what the risks are.',
   '{"difficulty":"senior","tags":["bundling","pricing"]}'),
  ('strategy_business', 'How should Amazon approach a new emerging market?',
   'Amazon is considering a major push into a new emerging market. How would you think about the strategy?',
   '{"difficulty":"senior","tags":["market_entry","emerging_markets"]}'),
  ('strategy_business', 'Should Amazon build a health-tracking wearable?',
   'Make the strategic case for or against Amazon building a health-tracking wearable device.',
   '{"difficulty":"senior","tags":["new_product","hardware"]}'),
  ('strategy_business', 'What role should physical stores play in Amazon''s long-term strategy?',
   'How should Amazon think about physical retail stores as part of its long-term strategy?',
   '{"difficulty":"senior","tags":["omnichannel","long_term"]}'),

  -- ---------- estimation (new, +10) ----------
  ('estimation', 'Estimate how many packages Amazon delivers in the US per day.',
   'Walk through your assumptions and math to estimate Amazon''s daily package volume in the United States.',
   '{"difficulty":"mid","tags":["market_sizing","logistics"]}'),
  ('estimation', 'Estimate the number of Prime members in the United States.',
   'Estimate how many people in the US have an active Amazon Prime membership.',
   '{"difficulty":"mid","tags":["market_sizing","membership"]}'),
  ('estimation', 'Estimate Amazon''s daily revenue from a single large metro area.',
   'Pick a large US metro area and estimate Amazon''s daily retail revenue from it.',
   '{"difficulty":"senior","tags":["market_sizing","revenue"]}'),
  ('estimation', 'Estimate how many Alexa devices are actively used each day.',
   'Estimate the number of Alexa-enabled devices that are used on a typical day.',
   '{"difficulty":"mid","tags":["market_sizing","alexa"]}'),
  ('estimation', 'Estimate the storage capacity of one Amazon fulfillment center.',
   'Estimate how many items a single large Amazon fulfillment center can hold.',
   '{"difficulty":"senior","tags":["operations","capacity"]}'),
  ('estimation', 'Estimate how many customer service agents Amazon needs during the holidays.',
   'Estimate the number of customer service agents Amazon needs to staff during peak holiday season.',
   '{"difficulty":"mid","tags":["operations","staffing"]}'),
  ('estimation', 'Estimate the number of searches on Amazon.com per day.',
   'Estimate how many product searches are performed on Amazon.com in a single day.',
   '{"difficulty":"mid","tags":["market_sizing","search"]}'),
  ('estimation', 'Estimate how much Amazon spends on cardboard boxes per year.',
   'Estimate Amazon''s annual spend on shipping boxes.',
   '{"difficulty":"senior","tags":["cost_estimation","packaging"]}'),
  ('estimation', 'Estimate the number of delivery vans needed in a mid-sized city.',
   'Estimate how many delivery vans Amazon needs to serve a mid-sized city on a typical day.',
   '{"difficulty":"mid","tags":["operations","logistics"]}'),
  ('estimation', 'Estimate the annual revenue of a single Amazon Go store.',
   'Estimate how much revenue one Amazon Go convenience store generates per year.',
   '{"difficulty":"senior","tags":["market_sizing","retail"]}')
) as v(type, title, description, metadata)
where not exists (
  select 1 from questions q where q.title = v.title
);
